### ISSUE TITLE
Indentation Error

### ISSUE THREAD

**Issue by AkiMosi** [naveen7v/Bhavcopy#1]
Hello, the code would be super helpful. But when I tried to run in found some error.
There is a problem with indentation below the if statement under in line 57

Hope that you would correct it soon

Thank You

**Comment by naveen7v** [comment]
Hello, sorry for the late reply.
Can you please let me know which script or py file is causing this issue?

**Comment by naveen7v** [comment]
@AkiMosi - I found the mistake in bhavcopy.py file and its fixed now. Hope this helps

**Comment by AkiMosi** [comment]
hey @naveen7v thank you so much....
